Assert that only one subscription exists
Users that mistakenly misconfigure and create two instances (or more)
of the subscription resource causes some gather scripts to fail.

For example, with 2 different sriov subscriptions, the SRIOV_NS will equal
"openshift-sriov-network-operatoropenshift-sriov-network-operator"
which is invalid.

Here we add "{{\n}}" and with that, check whether we found more than
one subscription, and if so, exit with an error.

This fix is applied to all of the gather scripts that use this method:
ingress_node_firewall, metallb, network_observability, nmstate and sriov

Signed-off-by: liornoy <lnoy@redhat.com>
Co-authored-by: Vladislav Walek <22072258+vwalek@users.noreply.github.com>

diff --git a/collection-scripts/gather_network_observability b/collection-scripts/gather_network_observability
--- a/collection-scripts/gather_network_observability
+++ b/collection-scripts/gather_network_observability
@@ -1,10 +1,15 @@
 #!/bin/bash
 BASE_COLLECTION_PATH="must-gather"
-NO_NS="$(oc get subs -A -o template --template '{{range .items}}{{if eq .spec.name "netobserv-operator"}}{{.metadata.namespace}}{{end}}{{end}}')"
+NO_NS="$(oc get subs -A -o template --template '{{range .items}}{{if eq .spec.name "netobserv-operator"}}{{.metadata.namespace}}{{"\n"}}{{end}}{{end}}')"
 
 if [ -z "${NO_NS}" ]; then
     echo "INFO: Network Observability namespace is not detected. Skipping."
     exit 0
+fi
+
+if [[ "$(echo "${NO_NS}" | wc -l)">1 ]]; then
+    echo "ERROR: found more than one netobserv-operator subscription. Exiting."
+    exit 1
 fi
 
 function get_netobserv_cluster_crs() {
