Added extra safeguards

diff --git a/collection-scripts/gather_etcd b/collection-scripts/gather_etcd
--- a/collection-scripts/gather_etcd
+++ b/collection-scripts/gather_etcd
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+#Safeguards
+set -o nounset
+set -o errexit
+set -o pipefail
+
 BASE_COLLECTION_PATH="/must-gather"
 ETCD_LOG_PATH="${BASE_COLLECTION_PATH}/etcd_info"
 
@@ -25,6 +30,9 @@ echo "Using endpoints: ${ETCDCTL_ENDPOINTS}"
 mkdir -p ${ETCD_LOG_PATH}
 
 echo "INFO: Starting getting etcd information"
+
+# If one ocp4etcdctl execution fails, the other ones should be tried anyway.
+set +o errexit
 
 PIDS=()
 
